# Generated by Django 3.2.16 on 2022-12-18 12:22

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="YTChannel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "channel_id",
                    models.CharField(
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Channel Id",
                    ),
                ),
                (
                    "channel_title",
                    models.CharField(max_length=100, verbose_name="Channel Title"),
                ),
            ],
            options={
                "verbose_name": "yt_channel",
                "verbose_name_plural": "yt_channels",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="YTVideo",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "video_id",
                    models.CharField(
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Video Id",
                    ),
                ),
                (
                    "video_title",
                    models.CharField(max_length=250, verbose_name="Video Title"),
                ),
                (
                    "video_description",
                    models.TextField(verbose_name="Channel Description"),
                ),
                (
                    "video_published_at",
                    models.DateTimeField(verbose_name="Channel Published At"),
                ),
                (
                    "video_etag",
                    models.CharField(max_length=50, verbose_name="Channel Etag"),
                ),
                (
                    "video_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="channel",
                        to="youtube.ytchannel",
                    ),
                ),
            ],
            options={
                "verbose_name": "yt_video",
                "verbose_name_plural": "yt_videos",
                "ordering": ("-video_published_at",),
            },
        ),
        migrations.CreateModel(
            name="YTThumbnail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "thumbnail_url",
                    models.CharField(max_length=100, verbose_name="Thumbnail URL"),
                ),
                (
                    "thumbnail_width",
                    models.PositiveSmallIntegerField(verbose_name="Thumbnail width"),
                ),
                (
                    "thumbnail_height",
                    models.PositiveSmallIntegerField(verbose_name="Thumbnail height"),
                ),
                (
                    "thumbnail_type",
                    models.PositiveBigIntegerField(
                        choices=[
                            (0, "DEFAULT"),
                            (1, "MEDIUM"),
                            (2, "HIGH"),
                            (3, "STANDARD"),
                            (4, "MAXRES"),
                        ],
                        verbose_name="Thumbnail type",
                    ),
                ),
                (
                    "thumbnail_video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thumbnails",
                        to="youtube.ytvideo",
                    ),
                ),
            ],
            options={
                "verbose_name": "yt_thumbnail",
                "verbose_name_plural": "yt_thumbnails",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="ytvideo",
            index=models.Index(
                fields=["video_title"], name="youtube_ytv_video_t_54439f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ytvideo",
            index=models.Index(
                fields=["video_description"], name="youtube_ytv_video_d_86925e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ytvideo",
            index=models.Index(
                fields=["video_published_at"], name="youtube_ytv_video_p_776846_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ytthumbnail",
            constraint=models.UniqueConstraint(
                fields=("thumbnail_video", "thumbnail_type", "thumbnail_url"),
                name="yt_thumbnail_primary_keys",
            ),
        ),
    ]
